"""Constants for RD200 BLE."""

DOMAIN = "rd200_ble"

VOLUME_BECQUEREL = "Bq/m³"
VOLUME_PICOCURIE = "pCi/L"
COUNT_PULSES = "Pulses"

DEFAULT_SCAN_INTERVAL = 600

CONF_KEEP_LAST_VALID_VALUE = "keep_last_valid_value"
CONF_MAX_CACHE_AGE_HOURS = "max_cache_age_hours"

DEFAULT_KEEP_LAST_VALID_VALUE = False
DEFAULT_MAX_CACHE_AGE_HOURS = 0
